src/deployer.ts
src/exported.ts

What does this PR do?
Adds `Deployables` class
What issues does this PR fix or reference?
@W-9225351@

feat: add Deployables class

---

package.json
src/util.ts
test/unit/util.test.ts
yarn.lock

fix: correct header to data column alignment

---

CHANGELOG.md
README.md
package.json
src/deployer.ts
src/exported.ts
src/hooks.ts
src/types/index.ts
yarn.lock

Rename to sf-plugins-core

---

package.json
src/util.ts
test/unit/util.test.ts
yarn.lock

feat: add help section helper function

---

src/deauthorizer.ts
src/exported.ts
src/hooks.ts
src/types/index.ts

Add hook for `sf logout`
@W-9890002@

feat: add logout hook

---

src/deauthorizer.ts

Add comments for deauthorizer methods

---

.git2gus/config.json

chore: config repo for git2gus

---

package.json
src/exported.ts
src/sfCommand.ts
yarn.lock

fix: move sf command to this repo

---

package.json
src/types/index.ts
yarn.lock

fix: add environment type to env list

---

package.json
yarn.lock

Official 1.0.0 release of `@salesforce/sf-plugins-core`

chore: 1.0.0

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
LICENSE.txt
package.json
src/types/index.ts
yarn.lock

fix: bump dependencies

---

LICENSE.txt
README.md
package.json
src/deauthorizer.ts
src/deployer.ts
src/hooks.ts
src/types/index.ts
yarn.lock

chore: update readme

---

package.json
src/flags/orgFlags.ts
yarn.lock

adds defaultHelp functions for orgFlags to show username instead of ObjectObject

feat: friendly default help for org flags

---

src/sfCommand.ts

fix: expose styledHeader as func in sf command

---

src/sfCommand.ts

fix: return error - dont throw

---

src/sfCommand.ts

feat: suppress progress bar output with env vars

---

src/exported.ts
src/sfCommand.ts

fix: expose flags enum and timed prompt

---

package.json
src/flags/orgFlags.ts
src/sfCommand.ts
src/ux/prompter.ts
yarn.lock

@W-10749241@ 
simplified confirm on Prompter
update logic for "is it a devHub"
fix logic error on timedPrompt ms being unused
require higher oclif/core so ux.stylizedHeader tests don't fail

feat: confirm on Prompter

---

messages/messages.md

found in https://github.com/salesforcecli/plugin-env/pull/252
[@W-10749241@](https://gus.lightning.force.com/a07EE00000rabTxYAI)

feat: explain what a valid api version looks like

---

messages/messages.md
package.json
src/exported.ts
src/sfCommand.ts
test/unit/sfCommand.test.ts
yarn.lock

fix: adjust message formats

---

src/flags/orgFlags.ts

fix: optional orgs can be undefined

---

src/flags/orgFlags.ts

fix: need await in order for the catch to be effective

---

src/flags/orgApiVersion.ts
src/flags/orgFlags.ts

fix: update config vars

---

messages/messages.md
package.json
yarn.lock

fix: update error message

---

package.json
src/flags/duration.ts
src/flags/orgApiVersion.ts
src/flags/orgFlags.ts
src/flags/salesforceId.ts
yarn.lock

Allows the flag type to change based on whether or not the flag is required or has a default value

Add function overloads to custom flags

---

messages/messages.md
src/exported.ts
src/util.ts
test/unit/util.test.ts

Add optional support for varargs
@W-11872285@

feat: support varargs

---

src/sfCommand.ts

I think I like this option better
* **doesn't require command users to know about what the hooks are in other plugins or in libraries**
* looks at hooks from plugins
* subscribes to lifecycle events based on those hook names
* ignores oclif plugins and telemetry
@W-12069098@
This could get un-perfy depending on how many hooks are in place.
It could be enhanced by finding a way to exclude more hooks that we don't intend to be used by customers (ex: the sf hooks meant for communication between various products/clouds).  These could be hardcoded--not sure if there's a good way say which hooks are "internal" or which ones want to follow lifecycle events without getting stuff into oclif that doesn't belong.
QA: probably worth trying to compare perf on the 2 options.  
I have a branch on …

feat: subscribe existing hooks to matching events

---

messages/messages.md
src/flags/salesforceId.ts
test/unit/flags/id.test.ts

@W-12346910@
Modify id flag to support length of type ‘both’

fix: add ‘both’ type to id flag

---

src/flags/orgFlags.ts
test/unit/flags/orgFlags.test.ts

fix no inputs, with default org to return undefined for hub org

fix: no default hub with default org

---

package.json
src/deployer.ts
src/exported.ts
src/hooks.ts
src/sfCommand.ts
src/ux/progress.ts
src/ux/prompter.ts
src/ux/spinner.ts
src/ux/ux.ts
test/unit/flags/apiVersion.test.ts
test/unit/flags/duration.test.ts
test/unit/flags/id.test.ts
test/unit/ux/spinner.test.ts
test/unit/ux/ux.test.ts
yarn.lock

Upgrades to oclif/core@v2.
Breaking change because it removes `Flags.enum`
@W-10791948@

feat: use @oclif/core v2

---

package.json
yarn.lock

fix a bug needed for @W-11976561@

chore: bump oclif core for fix

---

.github/workflows/test.yml
package.json
src/sfCommand.ts
yarn.lock

fix: _run type

---

package.json
yarn.lock

feat!: drop node 14 support

---

src/sfCommand.ts
src/ux/ux.ts

[@W-12635880@](https://gus.lightning.force.com/a07EE00001MPBzUYAX)
https://github.com/forcedotcom/cli/issues/1974

fix: don't truncate tables by default

---

package.json
src/ux/progress.ts
yarn.lock

requires https://github.com/oclif/core/pull/710
parameterize noTTY.
[@W-13131360@](https://gus.lightning.force.com/a07EE00001QXN1iYAH)

feat: smarter progress defaults, including noTTY

---

README.md
package.json
src/stubUx.ts
yarn.lock

jsdoc with examples for all the stubUx functions.  
That'll get published into the [docs](https://salesforcecli.github.io/sf-plugins-core/functions/stubUx.stubPrompter.html) once it merges.
also added a link from here: https://github.com/salesforcecli/cli/wiki/Test-Your-Plugin#unit-tests-for-commands
@W-13631504@

fix(deps): remove hooks docs, add docs for stubUx functions, bump deps

---

src/sfCommand.ts

fix(perf): 2 fs ops in parallel

---

package.json
test/unit/sfCommand.test.ts
test/unit/stubUx.test.ts
yarn.lock

[@W-14085765@](https://gus.lightning.force.com/a07EE00001a9pRDYAY)

fix(deps)!: node 18, sfdx-core6

---

messages/messages.md

flag summary change
@W-14512755@
https://github.com/forcedotcom/cli/issues/2538

fix: docs about required flags that read from config

---

src/errorHandling.ts
src/sfCommand.ts
test/unit/errorHandling.test.ts

handles gack/typeError stuff in 442
that PR merged into a branch that got closed and never made it in
@W-14408683@
@W-14408677@

feat: oclif error code handling

---

package.json
yarn.lock

bump `@salesforce/core` version to latest

fix: bump to latest core lib

---

package.json
yarn.lock

bump core to latest
@W-14870123@

fix: bump version of core to 6.5.0

---

package.json
yarn.lock

fix: bump core version

---

package.json
src/sfCommand.ts
yarn.lock

Add the data property to the error used for telemetry..
@W-15758926@

fix: propagate data from original error

---

package.json
yarn.lock

fix!: core8

---

package.json
yarn.lock

update dependencies
@W-18033709@

W-18033709 - fix: update libs

---

package.json
yarn.lock

bump to latest `@salesforce/core` version
@W-18539941@

fix: update to latest sfdx-core - W-18539941

---

package.json
test/unit/errorFormatting.test.ts
yarn.lock

fix: bump deps @W-19178921@
