messages/messages.md, package.json, src/sfCommand.ts, yarn.lock
- Adds `logSensitive` to `SfCommand` so that commands can log a warning to the user before logging sensitive information (e.g. access tokens)
- Capture warnings in `SfCommand` so that we can put them in json output
=> feat: logSensitive, capture warnings

src/sfCommand.ts, src/ux.ts
Expose spinner related methods in `SfCommand`
```typescript
import { SfCommand } from '@salesforce/sf-plugins-core';
import { sleep } from '@salesforce/kit';
export default class MyCommand extends SfCommand {
public async run(): Promise<void> {
this.spinner.start('Doing some stuff');
await sleep(5000);
this.spinner.stop('Success');
}
}
```
@W-10330464@
=> feat: add spinner methods

messages/messages.md, src/sfCommand.ts
Add a `requiresProject` property, allowing commands to throw an error if it's not run inside a Salesforce project directory
@W-10024521@
=> feat: add requiresProject property

package.json, src/util.ts, yarn.lock
Makes the types on `toHelpSection` more friendly so that we don't run into the `This is likely not portable. A type annotation is necessary` compilation error when linking sf-plugins-core to a plugin
=> fix: make toHelpSection types more friendly

src/ux/prompter.ts
Adds a `timedPrompt` method to `Prompter`, so that we can timeout prompts when necessary
@W-10713661@
=> feat: add timedPrompt method

src/flags/duration.ts, src/flags/orgFlags.ts, src/flags/salesforceId.ts
Special flags should extend `Interfaces.OptionFlag` so that they can use the `exactlyOne` property
=> fix: use OptionFlag interface so that exactlyOne can be used

src/sfCommand.ts
Log errors to stderr. Doing so fixes various NUTs that were running assertions on the content in stderr
=> fix: log errors to stderr

messages/messages.md, src/sfCommand.ts
Warn users if they're using a beta command:
```
~/repos/salesforcecli/sample-project-multiple-packages [main] : ~/repos/salesforcecli/plugin-deploy-retrieve/bin/dev deploy metadata validate -d force-app
Warning: This command is currently in beta. Any aspect of this command is likely to change without advanced notice. Please do not rely on beta commands for scripting.
```
@W-10895477@
=> feat: warn users when using a beta command

package.json, src/util.ts, test/unit/util.test.ts, yarn.lock
Allow commands to generate help sections with arbitrary data. This is primarily to support the error codes section of help
```typescript
export default class DeployMetadata extends SfCommand<DeployMetadataResult> {
public static errorCodes = toHelpSection('ERROR CODES', {
0: 'The deploy succeeded.',
1: 'The deploy failed.',
});
}
```
```
ERROR CODES
0 The deploy succeeded.
1  The deploy failed.
```
=> feat: support error codes help section

package.json, src/ux/progress.ts, yarn.lock
Prevent multiple calls to `this.start` on the same instance of `Progress`. This resolves the issue of the deploy commands hanging indefinitely.
@W-10877276@
=> fix: prevent multiple starts of progress bar

package.json, src/sfCommand.ts, yarn.lock
for plugins to override the `catch` method, they need to catch errors that might occur (base js Error class or SfError) rather than the interface here (which should be the output).
required for @W-10749124@
=> feat: catch method supports base and SfError

.circleci/config.yml, package.json, src/flags/duration.ts, src/flags/orgApiVersion.ts, src/flags/orgFlags.ts, src/flags/salesforceId.ts, yarn.lock
Updates custom flags to use new `Flags.custom`
Depends on https://github.com/oclif/core/pull/473
@W-11632040@
=> feat: update custom flag definitions

src/util.ts, test/unit/util.test.ts
When I looked into this a bit more, I don't think a Generic is the correct solution for this. `argv` is always going to be an array of strings based on the [type in the ParseOutput](https://github.com/oclif/core/blob/main/src/interfaces/parser.ts#L59). Since we are returning parsed `argv` values, we can assume they'll be a string (or `undefined` set by this validator util if a value is not provided). 
Let me know if you feel I am missing something.
=> fix: parse varargs response type

src/sfCommand.ts, src/ux/ux.ts, test/unit/ux/ux.test.ts
Make `Ux` class more explicit about enabling output
=> feat: improve Ux options

messages/messages.md, src/compatibility.ts, src/flags/orgFlags.ts
This PR adds flag descriptions to all the sfdx org flags. Consumers can't set properties so the flags always showed up without a desc in the help text.
top: latest sf-plugins-core using `requiredOrgFlagWithDeprecations` flag
bottom: `requiredOrgFlagWithDeprecations` with desc
=> fix: add `summary` field to org flags

messages/messages.md
Updates `--loglevel` warn msg to mention `SFDX_LOG_LEVEL` env var as an alternative to set the log level for all loggers.
sfdx-core: https://github.com/forcedotcom/sfdx-core/blob/02e51c10d113f80385c82996595b4e77a9710d6b/src/logger.ts#L518
env var docs: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm
logging section - plugin dev guide:
https://github.com/salesforcecli/cli/wiki/Code-Your-Plug-In#logging-levels
=> fix: update loglevel warn msg to mention env var

src/compatibility.ts, src/flags/orgFlags.ts
for commands that use the required org/hub flag (or the ones from Compatibility) 
those are now marked as with the oclif `required` property 
so that their types appear correctly
before: Org | undefined
after: Org
=> fix: required flags use `required` for oclif types

src/sfCommand.ts
=> feat: add default answer param to confirm

package.json, src/hooks.ts, yarn.lock
Don't allow hooks to exit process
Depends on https://github.com/oclif/core/pull/620
=> fix: dont allow hooks to exit process

src/sfCommand.ts
- Throws error from `catch` so that unit tests can use `shouldThrow`
- Removes `SfError` instance checks in `catch` to prevent testing issues with multiple versions of sfdx-core being used across the dependency tree
=> fix: throw from catch

src/sfCommand.ts
Throw an actual `SfError` from `catch` method
=> fix: throw SfError from catch

package.json, src/sfCommand.ts, yarn.lock
Tell oclif to skip error handling for errors thrown from `SfCommand.catch`
Depends on https://github.com/oclif/core/pull/642
@W-12615284@
=> fix: add skipOclifErrorHandling to errors thrown from SfCommand.catch

src/sfCommand.ts
Emit `sfCommandError` event for plugin-telemetry to pick up
@W-12370126@
=> fix: emit sfCommandError event

src/sfCommand.ts
Adds more properties to the error caught in SfCommand to support push --json errors.
@W-13100374@
=> fix: add more error properties to support push errors

src/sfCommand.ts, test/unit/sfCommand.test.ts
`SFDX_CONTENT_TYPE` makes json in sfdxCommand, but wasn't in SfCommand.
extends oclif/core/command's jsonEnabled() method but adds additional criteria that arrive at `true`
note: this is refers to SF_CONTENT_TYPE but a pending change to sfdx-core translates the env from SFDX and provides a warning.  https://github.com/forcedotcom/sfdx-core/pull/817/files#diff-2a7aeba6131c233030f6f8f21990a6c6b01e15af4eb62714237f8f13b06ca000
@W-13097825@
=> fix: support setting json = true via env

messages/messages.md, src/flags/duration.ts, test/unit/flags/duration.test.ts
https://github.com/forcedotcom/cli/issues/2109
@W-13147602@
=> fix: nicer error messages for duration min/max violations

src/sfCommand.ts, test/unit/sfCommand.test.ts
- stop any spinners to prevent it from unintentionally swallowing output.
- If there is an active spinner, it'll say "Error" (in our standard red color) instead of "Done" for clarity
@W-14095032@
https://github.com/forcedotcom/cli/issues/2434
=> fix: stop spinners on caught error

package.json, src/exported.ts, src/ux/index.ts, src/ux/prompter.ts
Export `Separator` so that plugins don't have to depend on `inquirer` just to use it
=> feat: export inquirer Separator

src/sfCommand.ts
=> fix: add ctrl+c 130 listener

.github/workflows/test.yml, src/sfCommand.ts
`SfError` adds `exitCode: 1` by default which means that our configured exit codes for oclif-level errors are being ignored. This PR switches the logic to check for `oclif.exit` before checking `exitCode`
=> fix: check oclif exit code first

src/flags/duration.ts, test/unit/flags/duration.test.ts
fixes: https://github.com/salesforcecli/plugin-data/actions/runs/7201478307/job/19617799092
=> fix: allow zero default duration flags

package.json, yarn.lock
bump `@salesforce/core` to v6.6.0
=> fix: bump core to 6.6.0

src/flags/duration.ts
Set `defaultHelp` on `duration` flag so that we get a human readable string in the help output
@W-14625639@
=> fix: set defaultHelp on duration flag

messages/messages.md, src/sfCommand.ts
Add `--flags-dir` as a base flag for all commands that extend `SfCommand`
Breaking change because abstract classes that extend `SfCommand` **and** define `baseFlags` will fail typescript compilation. Solution is to spread `SfCommand.baseFlags` onto your abstract class' `baseFlags`. Example
```typescript
// src/base-command.ts
import {SfCommand, Flags} from '@salesforce/sf-plugins-core'
export abstract class BaseCommand extends SfCommand {
public static baseFlags = {
...SfCommand.baseFlags,
'global-flag': Flags.boolean()
} 
}
// src/commands/my-command.ts
import {BaseCommand} from '../base-command.ts'
import {Flags} from '@salesforce/sf-plugins-core'
export default class MyCommand extends BaseCommand {
public static flags = {
'my-flag': Flags.boolean()
}
public async run(): Promise<void> { …
```
=> feat!: add flags-dir base flag

src/errorHandling.ts, src/sfCommand.ts, test/unit/errorHandling.test.ts
the error catch on SfError is doing some transformation for sfError.  
it's possible to have a `context: undefined` on the sfError.
in existing logic for `context in error` to return true (prop exists, not that it is necessarily defined)
`context: 'context' in error ? error.context : this.statics.name,`
so that context stays undefined
NUTs caught this here https://github.com/salesforcecli/plugin-source/actions/runs/8636061623/job/23675553032?pr=1153#step:13:246
Note: this could be a behavior change in SfError's handling of undefined context, but using sfCommand to ensure that context comes off the command also fixes it (and probably fixes it better since sfCommand has access to the command name that we use as a backup).
=> fix: extract handler transform for ut, handle undefined

src/sfCommand.ts
Pass the command id to the `sfCommandError` event so that plugin-telemetry doesn't record duplicate errors when two commands fail in the same process (e.g. a `plugins install` of a JIT plugin before running the provided command)
@W-15428397@
=> fix: pass command id to sfCommandError event

messages/messages.md, src/flags/orgFlags.ts
[@W-15895601@](https://gus.lightning.force.com/a07EE00001slw9jYAA)
caught by QA on https://github.com/salesforcecli/plugin-deploy-retrieve/pull/1028
=> feat: add a default summary for optional orgs

package.json, src/errorHandling.ts, src/sfCommand.ts, yarn.lock
1. major version some inquirer packages, trying to help with https://github.com/salesforcecli/cli/actions/runs/9324482843/job/25669790838?pr=1703#step:6:98
2. looks like node's `process.` types are getting smarter, saying that `.exitCode` could in fact be a string, so we handle that better since sf's `status` must be always be a number
=> fix(deps): major-version-inquirers, exit-code typing

messages/messages.md, package.json, src/compatibility.ts, src/errorHandling.ts, src/flags/duration.ts, src/ux/prompts.ts, test/unit/compatibility.test.ts, test/unit/errorHandling.test.ts, test/unit/flags/duration.test.ts, test/unit/flags/id.test.ts, test/unit/sfCommand.test.ts, test/unit/stubUx.test.ts, yarn.lock
Remove warning about using commas in array flags - it was never being hit in real life
Tests depend on https://github.com/oclif/core/pull/1148
@W-16343745@
https://github.com/forcedotcom/cli/issues/2928
=> fix: remove dead code

src/sfCommand.ts
Flush warnings sent via `Lifecycle.emitWarning` at the end of the command execution.
**Note** plugin-settings NUTs are failing because warnings are not ordered as they were before. Those nuts shouldn't depend on order
@W-16438012@
=> feat: flush intra-command warnings at the end

.github/workflows/test.yml, package.json, test/unit/ux/ux.test.ts, yarn.lock
- Bump @oclif/table
- Remove unneeded deps (used for the old table)
(plugin-signups tests are expected to fail until that plugin is migrated to the new major)
=> fix: bump oclif/table

src/ux/table.ts, src/ux/ux.ts, test/unit/ux/ux.test.ts
Add `Ux.makeTable` to get a formatted table as a string without printing to the console
@W-17229849@
=> feat: add makeTable method
